#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += vendor/xiaomi/chiron

PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    $(LOCAL_PATH)/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ChironS/Forte_ChironS_Bluetooth_cal.acdb \
    $(LOCAL_PATH)/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ChironS/Forte_ChironS_General_cal.acdb \
    $(LOCAL_PATH)/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ChironS/Forte_ChironS_Global_cal.acdb \
    $(LOCAL_PATH)/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ChironS/Forte_ChironS_Handset_cal.acdb \
    $(LOCAL_PATH)/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ChironS/Forte_ChironS_Hdmi_cal.acdb \
    $(LOCAL_PATH)/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ChironS/Forte_ChironS_Headset_cal.acdb \
    $(LOCAL_PATH)/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ChironS/Forte_ChironS_Speaker_cal.acdb \
    $(LOCAL_PATH)/proprietary/vendor/etc/acdbdata/ChironS/Forte_ChironS_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/ChironS/Forte_ChironS_workspaceFile.qwsp \
    $(LOCAL_PATH)/proprietary/vendor/etc/acdbdata/Forte/Forte_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Bluetooth_cal.acdb \
    $(LOCAL_PATH)/proprietary/vendor/etc/acdbdata/Forte/Forte_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_General_cal.acdb \
    $(LOCAL_PATH)/proprietary/vendor/etc/acdbdata/Forte/Forte_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Global_cal.acdb \
    $(LOCAL_PATH)/proprietary/vendor/etc/acdbdata/Forte/Forte_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Handset_cal.acdb \
    $(LOCAL_PATH)/proprietary/vendor/etc/acdbdata/Forte/Forte_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Hdmi_cal.acdb \
    $(LOCAL_PATH)/proprietary/vendor/etc/acdbdata/Forte/Forte_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Headset_cal.acdb \
    $(LOCAL_PATH)/proprietary/vendor/etc/acdbdata/Forte/Forte_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_Speaker_cal.acdb \
    $(LOCAL_PATH)/proprietary/vendor/etc/acdbdata/Forte/Forte_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Forte/Forte_workspaceFile.qwsp \
    $(LOCAL_PATH)/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/camera/chiron_imx386_semco_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/chiron_imx386_semco_chromatix.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/camera/chiron_ov5675_primax_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/chiron_ov5675_primax_chromatix.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/camera/chiron_ov5675_qtech_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/chiron_ov5675_qtech_chromatix.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/camera/dualcamera.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/dualcamera.png \
    $(LOCAL_PATH)/proprietary/vendor/etc/elliptic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/elliptic.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/qdcm_calib_data_jdi_fhd_video_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_jdi_fhd_video_dsi_panel.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    $(LOCAL_PATH)/proprietary/vendor/etc/sensors/sensor_def_qcomdev.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_qcomdev.conf \
    $(LOCAL_PATH)/proprietary/vendor/firmware/tas2559_s_uCDSP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tas2559_s_uCDSP.bin \
    $(LOCAL_PATH)/proprietary/vendor/firmware/tas2559_uCDSP.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/tas2559_uCDSP.bin \
    $(LOCAL_PATH)/proprietary/system_ext/etc/dpm/dpm.conf:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/dpm/dpm.conf \
    $(LOCAL_PATH)/proprietary/system_ext/etc/init/dpmd.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/dpmd.rc \
    $(LOCAL_PATH)/proprietary/system_ext/etc/permissions/com.qti.dpmframework.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qti.dpmframework.xml \
    $(LOCAL_PATH)/proprietary/system_ext/etc/permissions/dpmapi.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/dpmapi.xml \
    $(LOCAL_PATH)/proprietary/system_ext/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qcrilhook.xml \
    $(LOCAL_PATH)/proprietary/system_ext/etc/permissions/qti_libpermissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qti_libpermissions.xml \
    $(LOCAL_PATH)/proprietary/system_ext/etc/permissions/qti_permissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qti_permissions.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/cne/mwqem.conf:$(TARGET_COPY_OUT_VENDOR)/etc/cne/mwqem.conf \
    $(LOCAL_PATH)/proprietary/vendor/etc/cne/profileMwqem.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/profileMwqem.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile1.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile2.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile3.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile4.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile5.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile6.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile1.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile15.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile15.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile16.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile16.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile17.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile18.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile19.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile19.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile2.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile20.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile21.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile21.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile3.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile32.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile32.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile4.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile5.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile6.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile7.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile7.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile1.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile2.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile3.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile4.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile5.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile6.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/data/netmgr_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/netmgr_config.xml \
    $(LOCAL_PATH)/proprietary/vendor/etc/init/android.hardware.bluetooth@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.0-service-qti.rc \
    $(LOCAL_PATH)/proprietary/vendor/etc/init/android.hardware.drm@1.1-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.1-service.widevine.rc \
    $(LOCAL_PATH)/proprietary/vendor/etc/init/cnd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/cnd.rc \
    $(LOCAL_PATH)/proprietary/vendor/etc/init/dataadpl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataadpl.rc \
    $(LOCAL_PATH)/proprietary/vendor/etc/init/dataqti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataqti.rc \
    $(LOCAL_PATH)/proprietary/vendor/etc/init/dpmQmiMgr.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dpmQmiMgr.rc \
    $(LOCAL_PATH)/proprietary/vendor/etc/init/ims_rtp_daemon_legacy.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ims_rtp_daemon_legacy.rc \
    $(LOCAL_PATH)/proprietary/vendor/etc/init/imsdatadaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsdatadaemon.rc \
    $(LOCAL_PATH)/proprietary/vendor/etc/init/imsqmidaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsqmidaemon.rc \
    $(LOCAL_PATH)/proprietary/vendor/etc/init/imsrcsd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsrcsd.rc \
    $(LOCAL_PATH)/proprietary/vendor/etc/init/netmgrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netmgrd.rc \
    $(LOCAL_PATH)/proprietary/vendor/etc/init/qcrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qcrild.rc \
    $(LOCAL_PATH)/proprietary/vendor/etc/init/vendor.qti.hardware.alarm@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.alarm@1.0-service.rc \
    $(LOCAL_PATH)/proprietary/vendor/etc/init/vendor.qti.hardware.soter@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.soter@1.0-service.rc \
    $(LOCAL_PATH)/proprietary/vendor/etc/init/vendor.qti.rmt_storage.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.rmt_storage.rc \
    $(LOCAL_PATH)/proprietary/vendor/etc/init/vendor.qti.tftp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.tftp.rc \
    $(LOCAL_PATH)/proprietary/vendor/etc/init/vendor.xiaomi.hardware.mlipay@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.xiaomi.hardware.mlipay@1.1-service.rc \
    $(LOCAL_PATH)/proprietary/vendor/etc/seccomp_policy/imsrtp.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/imsrtp.policy \
    $(LOCAL_PATH)/proprietary/vendor/firmware/a530_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pfp.fw \
    $(LOCAL_PATH)/proprietary/vendor/firmware/a530_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pm4.fw \
    $(LOCAL_PATH)/proprietary/vendor/firmware/a540_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_gpmu.fw2 \
    $(LOCAL_PATH)/proprietary/vendor/firmware/a540_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.b00 \
    $(LOCAL_PATH)/proprietary/vendor/firmware/a540_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.b01 \
    $(LOCAL_PATH)/proprietary/vendor/firmware/a540_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.b02 \
    $(LOCAL_PATH)/proprietary/vendor/firmware/a540_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.elf \
    $(LOCAL_PATH)/proprietary/vendor/firmware/a540_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_zap.mdt \
    $(LOCAL_PATH)/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    $(LOCAL_PATH)/proprietary/vendor/firmware/ipa_fws.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b00 \
    $(LOCAL_PATH)/proprietary/vendor/firmware/ipa_fws.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b01 \
    $(LOCAL_PATH)/proprietary/vendor/firmware/ipa_fws.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b02 \
    $(LOCAL_PATH)/proprietary/vendor/firmware/ipa_fws.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b03 \
    $(LOCAL_PATH)/proprietary/vendor/firmware/ipa_fws.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b04 \
    $(LOCAL_PATH)/proprietary/vendor/firmware/ipa_fws.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.elf \
    $(LOCAL_PATH)/proprietary/vendor/firmware/ipa_fws.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.mdt \
    $(LOCAL_PATH)/proprietary/vendor/radio/qcril_database/qcril.db:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/qcril.db \
    $(LOCAL_PATH)/proprietary/vendor/radio/qcril_database/upgrade/0_initial.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/0_initial.sql \
    $(LOCAL_PATH)/proprietary/vendor/radio/qcril_database/upgrade/1_version_intro.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/1_version_intro.sql \
    $(LOCAL_PATH)/proprietary/vendor/radio/qcril_database/upgrade/10_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/10_version_update_ecc_table.sql \
    $(LOCAL_PATH)/proprietary/vendor/radio/qcril_database/upgrade/2_version_add_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/2_version_add_wps_config.sql \
    $(LOCAL_PATH)/proprietary/vendor/radio/qcril_database/upgrade/3_version_update_wps_config.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/3_version_update_wps_config.sql \
    $(LOCAL_PATH)/proprietary/vendor/radio/qcril_database/upgrade/4_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/4_version_update_ecc_table.sql \
    $(LOCAL_PATH)/proprietary/vendor/radio/qcril_database/upgrade/5_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/5_version_update_ecc_table.sql \
    $(LOCAL_PATH)/proprietary/vendor/radio/qcril_database/upgrade/6_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/6_version_update_ecc_table.sql \
    $(LOCAL_PATH)/proprietary/vendor/radio/qcril_database/upgrade/7_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/7_version_update_ecc_table.sql \
    $(LOCAL_PATH)/proprietary/vendor/radio/qcril_database/upgrade/8_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/8_version_update_ecc_table.sql \
    $(LOCAL_PATH)/proprietary/vendor/radio/qcril_database/upgrade/9_version_update_ecc_table.sql:$(TARGET_COPY_OUT_VENDOR)/radio/qcril_database/upgrade/9_version_update_ecc_table.sql

PRODUCT_PACKAGES += \
    adpl \
    adsprpcd \
    android.hardware.bluetooth@1.0-impl-qti \
    android.hardware.bluetooth@1.0-service-qti \
    android.hardware.drm@1.1-service.widevine \
    camera.msm8998 \
    cnd \
    CneApp \
    cnss-daemon \
    com.dsi.ant@1.0-impl \
    com.qti.dpmframework \
    com.qualcomm.qti.dpm.api@1.0 \
    com.qualcomm.qti.dpm.api@1.0_vendor \
    com.qualcomm.qti.imscmservice@2.0 \
    com.qualcomm.qti.imscmservice@2.1 \
    com.qualcomm.qti.imscmservice@2.2 \
    com.qualcomm.qti.uceservice@2.0 \
    com.qualcomm.qti.uceservice@2.1 \
    com.qualcomm.qti.uceservice@2.2 \
    com.qualcomm.qti.uceservice@2.3 \
    dirac_resource \
    dirac_resource_vendor \
    dpmapi \
    dpmd \
    dpmQmiMgr \
    dpmserviceapp \
    eglSubDriverAndroid \
    fingerprint.fpc.msm8998 \
    fingerprint.goodix.msm8998 \
    gatekeeper.msm8998 \
    hvdcp_opti \
    ims \
    ims_rtp_daemon \
    imsdatadaemon \
    imsqmidaemon \
    imsrcsd \
    irsc_util \
    IWlanService \
    keystore.msm8998 \
    lib_lowlight \
    lib_lowlight_dxo \
    lib-imscamera \
    lib-imscmservice \
    lib-imsdpl \
    lib-imsqimf \
    lib-imsrcs-v2 \
    lib-imsrcsbaseimpl \
    lib-imsSDP \
    lib-imsvideocodec \
    lib-imsvt \
    lib-imsvtcore \
    lib-imsvtextutils \
    lib-imsvtutils \
    lib-imsxml \
    lib-rcsconfig \
    lib-rtpcommon \
    lib-rtpcore \
    lib-rtpsl \
    lib-siputility \
    lib-uceservice \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libactuator_chiron_imx386_ak7372_semco \
    libadiertac \
    libadm \
    libadreno_utils \
    libadsp_default_listener \
    libadsp_fd_skel \
    libadsp_hvx_add_constant \
    libadsp_hvx_skel \
    libadsprpc \
    libapps_mem_heap \
    libarcsoft_beauty_shot \
    libarcsoft_beautyshot \
    libarcsoft_beautyshot_image_algorithm \
    libarcsoft_beautyshot_video_algorithm \
    libarcsoft_dualcam_optical_zoom \
    libarcsoft_dualcam_optical_zoom_control \
    libarcsoft_dualcam_refocus \
    libasphere \
    libaudcal \
    libbtnv \
    libC2D2 \
    libc2d30_bltlib \
    libCB \
    libchromatix_chiron_imx386_semco_4K_preview \
    libchromatix_chiron_imx386_semco_4K_video \
    libchromatix_chiron_imx386_semco_common \
    libchromatix_chiron_imx386_semco_cpp_hfr_120 \
    libchromatix_chiron_imx386_semco_cpp_hfr_60 \
    libchromatix_chiron_imx386_semco_cpp_hfr_90 \
    libchromatix_chiron_imx386_semco_cpp_liveshot \
    libchromatix_chiron_imx386_semco_cpp_preview \
    libchromatix_chiron_imx386_semco_cpp_snapshot \
    libchromatix_chiron_imx386_semco_cpp_snapshot_hdr \
    libchromatix_chiron_imx386_semco_cpp_snapshot_hht \
    libchromatix_chiron_imx386_semco_cpp_video \
    libchromatix_chiron_imx386_semco_cpp_video_hdr \
    libchromatix_chiron_imx386_semco_default_preview \
    libchromatix_chiron_imx386_semco_default_video \
    libchromatix_chiron_imx386_semco_hdr_snapshot_3a \
    libchromatix_chiron_imx386_semco_hdr_video_3a \
    libchromatix_chiron_imx386_semco_hfr_120 \
    libchromatix_chiron_imx386_semco_hfr_120_3a \
    libchromatix_chiron_imx386_semco_hfr_60 \
    libchromatix_chiron_imx386_semco_hfr_60_3a \
    libchromatix_chiron_imx386_semco_hfr_90 \
    libchromatix_chiron_imx386_semco_hfr_90_3a \
    libchromatix_chiron_imx386_semco_liveshot \
    libchromatix_chiron_imx386_semco_postproc \
    libchromatix_chiron_imx386_semco_preview \
    libchromatix_chiron_imx386_semco_snapshot \
    libchromatix_chiron_imx386_semco_snapshot_hdr \
    libchromatix_chiron_imx386_semco_video \
    libchromatix_chiron_imx386_semco_video_hdr \
    libchromatix_chiron_imx386_semco_zsl_preview \
    libchromatix_chiron_imx386_semco_zsl_video \
    libchromatix_chiron_ov5675_primax_a3_default_preview \
    libchromatix_chiron_ov5675_primax_a3_default_video \
    libchromatix_chiron_ov5675_primax_a3_hfr_120 \
    libchromatix_chiron_ov5675_primax_a3_hfr_60 \
    libchromatix_chiron_ov5675_primax_a3_hfr_90 \
    libchromatix_chiron_ov5675_primax_common \
    libchromatix_chiron_ov5675_primax_cpp_ds_chromatix \
    libchromatix_chiron_ov5675_primax_cpp_hfr_120 \
    libchromatix_chiron_ov5675_primax_cpp_hfr_60 \
    libchromatix_chiron_ov5675_primax_cpp_hfr_90 \
    libchromatix_chiron_ov5675_primax_cpp_liveshot \
    libchromatix_chiron_ov5675_primax_cpp_preview \
    libchromatix_chiron_ov5675_primax_cpp_snapshot \
    libchromatix_chiron_ov5675_primax_cpp_us_chromatix \
    libchromatix_chiron_ov5675_primax_cpp_video \
    libchromatix_chiron_ov5675_primax_cpp_video_full \
    libchromatix_chiron_ov5675_primax_default_video \
    libchromatix_chiron_ov5675_primax_hfr_120 \
    libchromatix_chiron_ov5675_primax_hfr_60 \
    libchromatix_chiron_ov5675_primax_hfr_90 \
    libchromatix_chiron_ov5675_primax_liveshot \
    libchromatix_chiron_ov5675_primax_postproc \
    libchromatix_chiron_ov5675_primax_preview \
    libchromatix_chiron_ov5675_primax_snapshot \
    libchromatix_chiron_ov5675_primax_video_full \
    libchromatix_chiron_ov5675_primax_zsl_preview \
    libchromatix_chiron_ov5675_primax_zsl_video \
    libchromatix_chiron_ov5675_qtech_a3_default_preview \
    libchromatix_chiron_ov5675_qtech_a3_default_video \
    libchromatix_chiron_ov5675_qtech_a3_hfr_120 \
    libchromatix_chiron_ov5675_qtech_a3_hfr_60 \
    libchromatix_chiron_ov5675_qtech_a3_hfr_90 \
    libchromatix_chiron_ov5675_qtech_common \
    libchromatix_chiron_ov5675_qtech_cpp_ds_chromatix \
    libchromatix_chiron_ov5675_qtech_cpp_hfr_120 \
    libchromatix_chiron_ov5675_qtech_cpp_hfr_60 \
    libchromatix_chiron_ov5675_qtech_cpp_hfr_90 \
    libchromatix_chiron_ov5675_qtech_cpp_liveshot \
    libchromatix_chiron_ov5675_qtech_cpp_preview \
    libchromatix_chiron_ov5675_qtech_cpp_snapshot \
    libchromatix_chiron_ov5675_qtech_cpp_us_chromatix \
    libchromatix_chiron_ov5675_qtech_cpp_video \
    libchromatix_chiron_ov5675_qtech_cpp_video_full \
    libchromatix_chiron_ov5675_qtech_default_video \
    libchromatix_chiron_ov5675_qtech_hfr_120 \
    libchromatix_chiron_ov5675_qtech_hfr_60 \
    libchromatix_chiron_ov5675_qtech_hfr_90 \
    libchromatix_chiron_ov5675_qtech_liveshot \
    libchromatix_chiron_ov5675_qtech_postproc \
    libchromatix_chiron_ov5675_qtech_preview \
    libchromatix_chiron_ov5675_qtech_snapshot \
    libchromatix_chiron_ov5675_qtech_video_full \
    libchromatix_chiron_ov5675_qtech_zsl_preview \
    libchromatix_chiron_ov5675_qtech_zsl_video \
    libcne \
    libcneapiclient \
    libcneoplookup \
    libconfigdb \
    libdataitems \
    libdiag \
    libdiag_system \
    libdirac \
    libdirac-capiv2 \
    libdpmctmgr \
    libdpmfdmgr \
    libdpmframework \
    libdpmqmihal \
    libdpmtcm \
    libdrmfs \
    libdrmtime \
    libdsi_netctrl \
    libdspCV_skel \
    libdsutils \
    libEGL_adreno \
    libFaceGrade \
    libfastcvadsp \
    libfastcvadsp_skel \
    libfastcvadsp_stub \
    libfastcvopt \
    libflash_pmic \
    libflp \
    libgeofence \
    libgf_ca \
    libgf_hal \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libGPreqcancel \
    libGPreqcancel_svc \
    libgpustats \
    libgsl \
    libhal_dbg \
    libhdr_tm \
    libidl \
    libimscamera_jni \
    libimsmedia_jni \
    libizat_core \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    liblbs_core \
    libllvm-glnext \
    libllvm-qcom \
    libloc_api_v02 \
    libloc_ds_api \
    liblqe \
    libmdmdetect \
    libmibokeh_835 \
    libMiCameraHal \
    libmlipay@1.1 \
    libmm-qcamera \
    libmmcamera_arcrtb_lib \
    libmmcamera_arcsoft_smoothtranstion_wrapper_lib \
    libmmcamera_chiron_imx386_semco \
    libmmcamera_chiron_imx386_semco_eeprom \
    libmmcamera_chiron_ov5675_primax \
    libmmcamera_chiron_ov5675_primax_eeprom \
    libmmcamera_chiron_ov5675_qtech \
    libmmcamera_chiron_ov5675_qtech_eeprom \
    libmmcamera_csidtg \
    libmmcamera_dbg \
    libmmcamera_dummyalgo \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_hdr_gb_lib \
    libmmcamera_hvx_add_constant \
    libmmcamera_hvx_grid_sum \
    libmmcamera_imglib \
    libmmcamera_imglib_faceproc_adspstub \
    libmmcamera_interface \
    libmmcamera_isp_abf48 \
    libmmcamera_isp_aec_bg_stats47 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats46 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_black_level48 \
    libmmcamera_isp_bpc48 \
    libmmcamera_isp_cac47 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct46 \
    libmmcamera_isp_color_xform_encoder46 \
    libmmcamera_isp_color_xform_video46 \
    libmmcamera_isp_color_xform_viewfinder46 \
    libmmcamera_isp_cs_stats46 \
    libmmcamera_isp_demosaic48 \
    libmmcamera_isp_demux48 \
    libmmcamera_isp_fovcrop_encoder46 \
    libmmcamera_isp_fovcrop_video46 \
    libmmcamera_isp_fovcrop_viewfinder46 \
    libmmcamera_isp_gamma44 \
    libmmcamera_isp_gic48 \
    libmmcamera_isp_gtm46 \
    libmmcamera_isp_hdr_be_stats46 \
    libmmcamera_isp_hdr_bhist_stats44 \
    libmmcamera_isp_hdr48 \
    libmmcamera_isp_ihist_stats46 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm47 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff44 \
    libmmcamera_isp_pdaf48 \
    libmmcamera_isp_pedestal_correct46 \
    libmmcamera_isp_rs_stats46 \
    libmmcamera_isp_scaler_encoder46 \
    libmmcamera_isp_scaler_video46 \
    libmmcamera_isp_scaler_viewfinder46 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_snr47 \
    libmmcamera_isp_sub_module \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_quadracfa \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_frame_algorithm \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_is \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_q3a_core \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_lib \
    libmmcamera2_stats_modules \
    libmmjpeg \
    libmmjpeg_interface \
    libmmlib2d_interface \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libmorpho_easy_hdr \
    libmorpho_hdr_checker \
    libmpbase \
    libnetmgr \
    libnetmgr_common \
    libnetmgr_nr_fusion \
    libnetmgr_rmnet_ext \
    libnlnetmgr \
    libois_bu63164 \
    libOmxVpp \
    libOpenCL \
    libpdmapper \
    libperipheral_client \
    libpn553_fw \
    libq3dtools_adreno \
    libq3dtools_esx \
    libqcmaputils \
    libqcrildatactl \
    libqcrilFramework \
    libqdi \
    libqdp \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_encdec \
    libqmiservices \
    libqomx_core \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libqrtr \
    libQSEEComAPI \
    libqseed3 \
    libqsocket \
    libQTapGLES \
    libqtigef \
    librcc \
    libremosaic_daemon \
    libril-qc-hal-qmi \
    libril-qc-logger \
    libril-qc-ltedirectdisc \
    libril-qc-radioconfig \
    libril-qcril-hook-oem \
    librilqmiservices \
    librpmb \
    libsdm-color \
    libsdm-diag \
    libsdm-disp-vndapis \
    libsdmextension \
    libsdsprpc \
    libsensor_reg \
    libsensor1 \
    libsettings \
    libsmwrapper \
    libsns_low_lat_stream_skel \
    libsns_low_lat_stream_stub \
    libsoc_helper \
    libSonyIMX386PdafLibrary \
    libspl \
    libssd \
    libsystem_health_mon \
    libthermalclient \
    libthermalioctl \
    libtime_genoff \
    libtinyxml2_1 \
    libvpp_frc \
    libvpp_svc_skel \
    libvpphvx \
    libvpplibrary \
    libvqzip \
    libwms \
    libwqe \
    libwvhidl \
    libXMFD_AgeGender \
    libxml \
    loc_launcher \
    lowi-server \
    mlipayd@1.1 \
    msm_irqbalance \
    netmgrd \
    pd-mapper \
    pm-proxy \
    pm-service \
    power_off_alarm \
    PowerOffAlarm \
    qcrild \
    qcrild_librilutils \
    qcrilhook \
    qcrilmsgtunnel \
    qrtr-cfg \
    qrtr-lookup \
    qrtr-ns \
    qseecomd \
    qti \
    qtibus \
    qtimutex \
    QtiTelephonyService \
    rmt_storage \
    sensors.elliptic \
    sensors.qti \
    sensors.ssc \
    SoterService \
    sound_trigger.primary.msm8998 \
    system_ext_priv-app_ims_lib_arm64_libimscamera_jni_so \
    system_ext_priv-app_ims_lib_arm64_libimsmedia_jni_so \
    tftp_server \
    time_daemon \
    TimeService \
    vendor_lib_libEGL_adreno_so \
    vendor_lib_libGLESv2_adreno_so \
    vendor_lib_libq3dtools_adreno_so \
    vendor_lib64_libEGL_adreno_so \
    vendor_lib64_libGLESv2_adreno_so \
    vendor_lib64_libq3dtools_adreno_so \
    vendor.qti.data.factory@2.0 \
    vendor.qti.data.factory@2.1 \
    vendor.qti.data.factory@2.2 \
    vendor.qti.data.factory@2.3 \
    vendor.qti.data.mwqem@1.0 \
    vendor.qti.data.slm@1.0 \
    vendor.qti.diaghal@1.0 \
    vendor.qti.hardware.alarm@1.0 \
    vendor.qti.hardware.alarm@1.0-impl \
    vendor.qti.hardware.alarm@1.0-service \
    vendor.qti.hardware.bluetooth_sar@1.0 \
    vendor.qti.hardware.bluetooth_sar@1.1 \
    vendor.qti.hardware.bluetooth_sar@1.1-impl \
    vendor.qti.hardware.btconfigstore@2.0-impl \
    vendor.qti.hardware.data.cne.internal.api@1.0 \
    vendor.qti.hardware.data.cne.internal.constants@1.0 \
    vendor.qti.hardware.data.cne.internal.server@1.0 \
    vendor.qti.hardware.data.connection@1.0 \
    vendor.qti.hardware.data.connection@1.1 \
    vendor.qti.hardware.data.dynamicdds@1.0 \
    vendor.qti.hardware.data.iwlan@1.0 \
    vendor.qti.hardware.data.latency@1.0 \
    vendor.qti.hardware.data.lce@1.0 \
    vendor.qti.hardware.data.qmi@1.0 \
    vendor.qti.hardware.fm@1.0 \
    vendor.qti.hardware.mwqemadapter@1.0 \
    vendor.qti.hardware.radio.am@1.0 \
    vendor.qti.hardware.radio.ims@1.0 \
    vendor.qti.hardware.radio.ims@1.1 \
    vendor.qti.hardware.radio.ims@1.2 \
    vendor.qti.hardware.radio.ims@1.3 \
    vendor.qti.hardware.radio.ims@1.4 \
    vendor.qti.hardware.radio.ims@1.5 \
    vendor.qti.hardware.radio.ims@1.6 \
    vendor.qti.hardware.radio.ims@1.7 \
    vendor.qti.hardware.radio.internal.deviceinfo@1.0 \
    vendor.qti.hardware.radio.lpa@1.0 \
    vendor.qti.hardware.radio.lpa@1.1 \
    vendor.qti.hardware.radio.qcrilhook@1.0 \
    vendor.qti.hardware.radio.qtiradio@1.0 \
    vendor.qti.hardware.radio.qtiradio@2.0 \
    vendor.qti.hardware.radio.qtiradio@2.1 \
    vendor.qti.hardware.radio.qtiradio@2.2 \
    vendor.qti.hardware.radio.qtiradio@2.3 \
    vendor.qti.hardware.radio.qtiradio@2.4 \
    vendor.qti.hardware.radio.uim_remote_client@1.0 \
    vendor.qti.hardware.radio.uim_remote_client@1.1 \
    vendor.qti.hardware.radio.uim_remote_client@1.2 \
    vendor.qti.hardware.radio.uim_remote_server@1.0 \
    vendor.qti.hardware.radio.uim@1.0 \
    vendor.qti.hardware.radio.uim@1.1 \
    vendor.qti.hardware.radio.uim@1.2 \
    vendor.qti.hardware.soter@1.0 \
    vendor.qti.hardware.soter@1.0-impl \
    vendor.qti.hardware.soter@1.0-service \
    vendor.qti.ims.callcapability@1.0 \
    vendor.qti.ims.callinfo@1.0 \
    vendor.qti.ims.factory@1.0 \
    vendor.qti.ims.factory@1.1 \
    vendor.qti.ims.rcsconfig@1.0 \
    vendor.qti.ims.rcsconfig@1.1 \
    vendor.qti.ims.rcsconfig@2.0 \
    vendor.qti.ims.rcsconfig@2.1 \
    vendor.qti.imsrtpservice@3.0 \
    vendor.qti.imsrtpservice@3.0_vendor \
    vendor.qti.imsrtpservice@3.0-service-Impl \
    vendor.qti.latency@2.0 \
    vendor.qti.latency@2.1 \
    vulkan.msm8998 \
    xtra-daemon
